CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  price FLOAT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);